apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Service
metadata:
  name: gf-ob-web-service
  namespace: stage
spec:
  type: NodePort
  selector:
    app: gf-ob-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gf-ob-web-deployment
  namespace: stage
  labels:
    app: gf-ob-web
  annotations:
    rollout: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gf-ob-web
  template:
    metadata:
      labels:
        app: gf-ob-web
    spec:
      containers:
        - name: golang
          image: mucunga90/gf-ob-web:stage
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
          envFrom:
            - secretRef:
                name: gf-ob-web-secret
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"