apiVersion: v1
kind: Service
metadata:
  name: gf-ob-web
  labels:
    app: gf-ob-web
spec:
  type: ClusterIP
  selector:
    app: gf-ob-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gf-ob-web
  labels:
    app: gf-ob-web
  annotations:
    rollout: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gf-ob-web
  template:
    metadata:
      labels:
        app: gf-ob-web
    spec:
      containers:
        - name: gf-ob-web
          image: mucunga90/gf-ob-web:prod
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 80

# kubectl delete service gf-ob-web-service 
# kubectl delete deployment gf-ob-web
# kubectl delete persistentvolumeclaim gf-ob-web-service-pv-claim
# kubectl delete persistentvolume gf-ob-web-service-pv-volume
