# Trigger the workflow only when:
# - a new pull request with any name/type is opened against the main, develop, hotfix/* or release/* branch
# - a commit is directly pushed to the pull request
  
name: Pull request builder
  
on:
  pull_request:
    branches:
      - main
      - hotfix/*
  
jobs:

  build_test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x] # We will deploy with only one version of node  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm build and test
        run: |
          npm install
          npm run build --if-present   

  setup:
    needs: [build_test]
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.vars.outputs.repo }}
      commit: ${{ steps.vars.outputs.commit }}
    steps:
      - name: Use repository
        uses: actions/checkout@v2
      - name: Build variables
        id: vars
        run: |
          echo "::set-output name=repo::$GITHUB_REPOSITORY"
          echo "::set-output name=commit::$(git rev-parse --short "$GITHUB_SHA")"
      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: |
            ${{ github.workspace }}/deploy
            ${{ github.workspace }}/build
            ${{ github.workspace }}/docker
            ${{ github.workspace }}/public
            ${{ github.workspace }}/src
            ${{ github.workspace }}/.dockerignore
            ${{ github.workspace }}/package.json

  